baseURL: "http://example.org/"
languageCode: "fr-fr"
title: "Maryame Bennani"
mainSections: ['pages']

ignoreFiles:
  - README.md
  - config.yml
  - LICENSE

menu:
  main:
    - name: À propos
      url: /a-propos/
      weight: -120
    - name: Études de cas
      url: /etude-de-cas/
      weight: -110
    - name: Contact
      url: /contact/
      weight: -100
